version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parkolohely_foglalas_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
    volumes:
      - sqlite_data:/app/prisma
    restart: unless-stopped

volumes:
  sqlite_data:
